AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy AWS resources including Lambda functions, DynamoDB table, and update Amazon Connect contact flow

Parameters:
  ConnectInstanceArn:
    Type: String
    Description: The ARN of the Amazon Connect instance

Resources:
  CustomerVanityNumbersDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CustomerVanityNumbers
      AttributeDefinitions:
        - AttributeName: PhoneNumber
          AttributeType: S
      KeySchema:
        - AttributeName: PhoneNumber
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                  - logs:*
                Resource: "*"

  VanityV2:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: VanityV2
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python312:6
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: VanityV2.zip

  GetVanityNumbers:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: getVanityNumbers
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Code:
        S3Bucket: your-lambda-code-bucket
        S3Key: GetVanityNumbers.zip

Resources:
  MyContactFlow:
    Type: AWS::Connect::ContactFlow
    Properties:
      Name: VanityNumber
      Description: "Vanity Number Contact Flow"
      InstanceArn: "arn:aws:connect:us-east-1:781368414427:instance/dd80ea0c-3ade-4b51-a814-45bff6db9292"
      Content: !Sub |
{
    "Version": "2019-10-30",
    "StartAction": "a1df37b2-f996-4fe1-b4af-a3529b119cad",
    "Metadata": {
        "entryPointPosition": {
            "x": 40,
            "y": 40
        },
        "ActionMetadata": {
            "a1df37b2-f996-4fe1-b4af-a3529b119cad": {
                "position": {
                    "x": 226.4,
                    "y": 72
                }
            },
            "8daf0793-f357-49ac-9b62-d031264e2249": {
                "position": {
                    "x": 1524,
                    "y": 776
                }
            },
            "7547c0f0-6524-4e3a-91f1-cd31f012855b": {
                "position": {
                    "x": 1092,
                    "y": 380.8
                }
            },
            "131a8333-6e6a-4af0-960c-5d69d0771dc7": {
                "position": {
                    "x": 819.2,
                    "y": 387.2
                },
                "parameters": {
                    "Attributes": {
                        "vanityNumber1": {
                            "useDynamic": true
                        },
                        "vanityNumber2": {
                            "useDynamic": true
                        },
                        "vanityNumber3": {
                            "useDynamic": true
                        },
                        "word1": {
                            "useDynamic": true
                        },
                        "word2": {
                            "useDynamic": true
                        },
                        "word3": {
                            "useDynamic": true
                        },
                        "definition1": {
                            "useDynamic": true
                        },
                        "definition2": {
                            "useDynamic": true
                        },
                        "definition3": {
                            "useDynamic": true
                        }
                    }
                },
                "dynamicParams": [
                    "vanityNumber1",
                    "vanityNumber2",
                    "vanityNumber3",
                    "word1",
                    "word2",
                    "word3",
                    "definition1",
                    "definition2",
                    "definition3"
                ]
            },
            "6a4468bd-a579-4911-9bee-b242ab095e4e": {
                "position": {
                    "x": 1249.6,
                    "y": 712
                }
            },
            "20449094-6ec4-4b0f-aa26-9215783c6405": {
                "position": {
                    "x": 220,
                    "y": 275.2
                }
            },
            "479c6b45-126b-4af9-aaf6-2a5769acb2b2": {
                "position": {
                    "x": 556.8,
                    "y": 390.4
                },
                "parameters": {
                    "LambdaFunctionARN": {
                        "displayName": "getVanityNumbers"
                    },
                    "LambdaInvocationAttributes": {
                        "Address": {
                            "useDynamic": true
                        }
                    }
                },
                "dynamicMetadata": {
                    "Address": true
                }
            },
            "41ccce4e-e7f4-461c-9f5a-7d1ec9ee48d1": {
                "position": {
                    "x": 212.8,
                    "y": 471.2
                },
                "parameters": {
                    "LambdaFunctionARN": {
                        "displayName": "VanityV2"
                    },
                    "LambdaInvocationAttributes": {
                        "Address": {
                            "useDynamic": true
                        }
                    }
                },
                "dynamicMetadata": {
                    "Address": true
                }
            }
        },
        "Annotations": [],
        "name": "VanityNumber",
        "description": "",
        "type": "contactFlow",
        "status": "published",
        "hash": {}
    },
    "Actions": [
        {
            "Parameters": {
                "FlowLoggingBehavior": "Enabled"
            },
            "Identifier": "a1df37b2-f996-4fe1-b4af-a3529b119cad",
            "Type": "UpdateFlowLoggingBehavior",
            "Transitions": {
                "NextAction": "20449094-6ec4-4b0f-aa26-9215783c6405"
            }
        },
        {
            "Parameters": {},
            "Identifier": "8daf0793-f357-49ac-9b62-d031264e2249",
            "Type": "DisconnectParticipant",
            "Transitions": {}
        },
        {
            "Parameters": {
                "SSML": "<speak>\n  Here are some vanity phone numbers and their meanings:\n  <break time=\"500ms\"/>\n  <p>\n    <s>Call <say-as interpret-as=\"telephone\">$.Attributes.vanityNumber1</say-as> ($.Attributes.word1) to $.Attributes.definition1.</s>\n  </p>\n  <break time=\"500ms\"/>\n  <p>\n    <s>Call <say-as interpret-as=\"telephone\">$.Attributes.vanityNumber2</say-as> ($.Attributes.word2) for $.Attributes.definition2.</s>\n  </p>\n  <break time=\"500ms\"/>\n  <p>\n    <s>Call <say-as interpret-as=\"telephone\">$.Attributes.vanityNumber3</say-as> ($.Attributes.word3) to $.Attributes.definition3.</s>\n  </p>\n</speak>\n"
            },
            "Identifier": "7547c0f0-6524-4e3a-91f1-cd31f012855b",
            "Type": "MessageParticipant",
            "Transitions": {
                "NextAction": "8daf0793-f357-49ac-9b62-d031264e2249",
                "Errors": [
                    {
                        "NextAction": "8daf0793-f357-49ac-9b62-d031264e2249",
                        "ErrorType": "NoMatchingError"
                    }
                ]
            }
        },
        {
            "Parameters": {
                "Attributes": {
                    "vanityNumber1": "$.External.vanityNumber1",
                    "vanityNumber2": "$.External.vanityNumber2",
                    "vanityNumber3": "$.External.vanityNumber3",
                    "word1": "$.External.word1",
                    "word2": "$.External.word2",
                    "word3": "$.External.word3",
                    "definition1": "$.External.definition1",
                    "definition2": "$.External.definition2",
                    "definition3": "$.External.definition3"
                },
                "TargetContact": "Current"
            },
            "Identifier": "131a8333-6e6a-4af0-960c-5d69d0771dc7",
            "Type": "UpdateContactAttributes",
            "Transitions": {
                "NextAction": "7547c0f0-6524-4e3a-91f1-cd31f012855b",
                "Errors": [
                    {
                        "NextAction": "7547c0f0-6524-4e3a-91f1-cd31f012855b",
                        "ErrorType": "NoMatchingError"
                    }
                ]
            }
        },
        {
            "Parameters": {
                "Text": "Error"
            },
            "Identifier": "6a4468bd-a579-4911-9bee-b242ab095e4e",
            "Type": "MessageParticipant",
            "Transitions": {
                "NextAction": "8daf0793-f357-49ac-9b62-d031264e2249",
                "Errors": [
                    {
                        "NextAction": "8daf0793-f357-49ac-9b62-d031264e2249",
                        "ErrorType": "NoMatchingError"
                    }
                ]
            }
        },
        {
            "Parameters": {
                "RecordingBehavior": {
                    "RecordedParticipants": [
                        "Agent",
                        "Customer"
                    ]
                }
            },
            "Identifier": "20449094-6ec4-4b0f-aa26-9215783c6405",
            "Type": "UpdateContactRecordingBehavior",
            "Transitions": {
                "NextAction": "41ccce4e-e7f4-461c-9f5a-7d1ec9ee48d1"
            }
        },
        {
            "Parameters": {
                "LambdaFunctionARN": "${LambdaArnGetVanityNumbers}",
                "InvocationTimeLimitSeconds": "8",
                "LambdaInvocationAttributes": {
                    "Address": "$.CustomerEndpoint.Address"
                },
                "ResponseValidation": {
                    "ResponseType": "STRING_MAP"
                }
            },
            "Identifier": "479c6b45-126b-4af9-aaf6-2a5769acb2b2",
            "Type": "InvokeLambdaFunction",
            "Transitions": {
                "NextAction": "131a8333-6e6a-4af0-960c-5d69d0771dc7",
                "Errors": [
                    {
                        "NextAction": "6a4468bd-a579-4911-9bee-b242ab095e4e",
                        "ErrorType": "NoMatchingError"
                    }
                ]
            }
        },
        {
            "Parameters": {
                "LambdaFunctionARN": "${LambdaArnVanityV2}",
                "InvocationTimeLimitSeconds": "8",
                "LambdaInvocationAttributes": {
                    "Address": "$.CustomerEndpoint.Address"
                },
                "ResponseValidation": {
                    "ResponseType": "STRING_MAP"
                }
            },
            "Identifier": "41ccce4e-e7f4-461c-9f5a-7d1ec9ee48d1",
            "Type": "InvokeLambdaFunction",
            "Transitions": {
                "NextAction": "479c6b45-126b-4af9-aaf6-2a5769acb2b2",
                "Errors": [
                    {
                        "NextAction": "479c6b45-126b-4af9-aaf6-2a5769acb2b2",
                        "ErrorType": "NoMatchingError"
                    }
                ]
            }
        }
    ]
}

Outputs:
  DynamoDBTableArn:
    Description: "ARN of the DynamoDB Table"
    Value: !GetAtt CustomerVanityNumbersDB.Arn

  VanityV2FunctionArn:
    Description: "ARN of the VanityV2 Lambda function"
    Value: !GetAtt VanityV2.Arn

  GetVanityNumbersFunctionArn:
    Description: "ARN of the GetVanityNumbers Lambda function"
    Value: !GetAtt GetVanityNumbers.Arn

  ContactFlowId:
    Description: "ID of the Contact Flow"
    Value: !GetRef MyContactFlow
